version: "3"
services:
  kurrant_v1_green:
    container_name: kurrant_v1_green
    image: dalicious77/kurrant_v1:${IMAGE_TAG}
    environment:
      - SPRING_PROFILES_ACTIVE=dev,dev-green,mail,sms,redis,jwt,s3,payment
    ports:
      - "8882:8882"
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "ap-northeast-2"
        awslogs-group: "kurrant/dev"
        awslogs-stream: "app"

    networks:
      - redis_redis_cluster