package co.dalicious.domain.user.entity.enums;

import exception.ApiException;
import exception.ExceptionEnum;
import lombok.Getter;

import java.util.Arrays;

@Getter
public enum Nation {

        REPUBLIC_OF_KOREA("대한민국", 1),
        GHANA("가나", 2),
        GABONG("가봉",3),
        GUYANA("가이아나", 4),
        GAMBIA("감비아", 5),
        GUERNSEY("건지", 6),
        GUADELOUPE("과델로프", 7),
        GUATEMALA("과테말라", 8),
        GUAM("괌", 9),
        HOLY_SEE("교황청", 10),
        GRENADA("그레나다", 11),
        GREECE("그리스", 12),
        GREENLAND("그린랜드", 13),
        EQUATORIAL_GUINEA("기네비소", 14),
        GUINEA("기니", 15),
        NAMIBIA("나미비아", 16),
        NAURU("나우루", 17),
        NIGERIA("나이지리아", 18),
        SOUTH_SUDAN("남수단", 19),
        SOUTH_AFRICA("남아프리카공화국", 20),
        SOUTH_GEORGIA_AND_SOUTH_SANDWICH_ISLANDS("남조지아 & 남샌드위치 군도", 21),
        NETHERLANDS("네덜란드", 22),
        NETHERLANDS_ANTILLES("네덜란드 열도", 23),
        NEPAL("네팔", 24),
        NORWAY("노르웨이", 25),
        NORFOLK_ISLAND("노폴크 아일랜드", 26),
        NEW_CALEDONIA("뉴 칼레도니아", 27),
        NEW_ZEALAND("뉴질랜드", 28),
        NIUE("니우에", 29),
        NIGER("니제르", 30),
        NICARAGUA("니카라과", 31),
        TAIWAN("대만", 32),
        DENMARK("덴마크", 33),
        DOMINICA("도미니카", 34),
        DOMINICAN_REPUBLIC("도미니카 공화국", 35),
        GERMANY("독일", 36),
        LAOS("라오스", 37),
        LIBERIA("라이베리아", 38),
        LATVIA("라트비아", 39),
        RUSSIAN_FEDERATION("러시아 연방", 40),
        LEBANON("레바논", 41),
        LESOTHO("레소토", 42),
        ROMANIA("루마니아", 43),
        LUXEMBOURG("룩셈부르그", 44),
        RWANDA("르완다", 45),
        LIBYA("리비아", 46),
        LITHUANIA("리투아니아", 47),
        LIECHTENSTEIN("리히텐슈타인", 48),
        MADAGASCAR("마다카스카르", 49),
        MARSHALL_ISLANDS("마샬군도", 50),
        MACEDONIA("마세도니아", 51),
        MINOR_OUTLYING_ISLANDS_OF_UNITED_STATES("마이너 아우틀링 합중국 군도", 52),
        MICRONESIA("마이크로네시아", 53),
        MACAO("마카오", 54),
        MARTINIQUE("마티니크", 55),
        MALAWI("말라위", 56),
        MALAYSIA("말레이시아", 57),
        MALI("말리", 58),
        MAN_ISLE_OF("맨섬", 59),
        MAYOTTE("메요트", 60),
        MEXICO("멕시코", 61),
        MONACO("모나코", 62),
        MOROCCO("모로코", 63),
        MAURITIUS("모리셔스", 64),
        MAURITANIA("모리타니", 65),
        MOZAMBIQUE("모잠비크", 66),
        MONTENEGRO("몬테네그로", 67),
        MONTSERRAT("몬트세라트", 68),
        MOLDOVA("몰도바", 69),
        MALDIVES("몰디브", 70),
        MALTA("몰타", 71),
        MONGOLIA("몽골", 72),
        UNITED_STATES_OF_AMERICA("미국", 73),
        MIDWAY_ISLANDS("미드웨이 군도", 74),
        US_VIRGIN_ISLANDS("미령 버진군도", 75),
        MYANMAR("미얀마", 76),
        VANUATU("바누아투", 77),
        BAHRAIN("바레인", 78),
        BARBADOS("바베이도스", 79),
        BAHAMAS("바하마", 80),
        BANGLADESH("방글라데시", 81),
        BERMUDA("버뮤다", 82),
        VENEZUELA("베네주엘라", 83),
        BENIN("베닝", 84),
        BELARUS("베라루스", 85),
        VIETNAM("베트남", 86),
        BELGIUM("벨기에", 87),
        BELIZE("벨리제", 88),
        BONAIRE_SINT_EUSTATIUS_AND_SABA("보네르 신트외스타티위스", 89),
        BOUVET_ISLAND("보빗군도", 90),
        BOSNIA_AND_HERZEGOVINA("보스니아-헤르체고비나", 91),
        BOTSWANA("보츠와나", 92),
        BOLIVIA("볼리비아", 93),
        BURUNDI("부룬디", 94),
        BURKINA_FASO("부르키나 파소", 95),
        BHUTAN("부탄", 96),
        NORTHERN_MARIANA_ISLANDS("북마리아나 군도", 97),
        NORTH_KOREA("북한", 98),
        BULGARIA("불가리아", 99),
        FRENCH_GUIANA("불령 가이아나", 100),
        FRENCH_SOUTHERN_AND_ANTARCTIC_LANDS("불령 남부지역", 101),
        FRENCH_REUNION("불령 리유니온 코모도 제도", 102),
        FRENCH_POLYNESIA("불령 폴리네시아", 103),
        BRAZIL("브라질", 104),
        BRUNEI("브루나이", 105),
        SAMOA("사모아", 106),
        SAUDI_ARABIA("사우디아라비아", 107),
        CYPRUS("사이프러스", 108),
        SAN_MARINO("산마리노", 109),
        SAO_TOME_AND_PRINCIPE("상토메 프린스페", 110),
        WESTERN_SAHARA("서사하라", 111),
        SENEGAL("세네갈", 112),
        SERBIA("세르비아", 113),
        SEYCHELLES("세이쉘", 114),
        SAINT_LUCIA("세인트 루시아", 115),
        SAINT_MARTIN("세인트 마틴", 116),
        SAINT_BARTHELEMY("세인트 바르탤르미", 117),
        SAINT_VINCENT_AND_THE_GRENADINES("세인트 빈센트 그레나딘", 118),
        SAINT_KITTS_AND_NEVIS("세인트 키츠 네비스", 119),
        SAINT_PIERRE_AND_MIQUELON("세인트 피레 미켈론", 120),
        SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA("세인트 헬레나", 121),
        SOMALIA("소말리아", 122),
        SOLOMON_ISLANDS("솔로몬 군도", 123),
        SUDAN("수단", 124),
        SURINAME("수리남", 125),
        SRI_LANKA("스리랑카", 126),
        SVALBARD_AND_JAN_MAYEN("스발비드 군도", 127),
        SWAZILAND("스와질랜드", 128),
        SWEDEN("스웨덴", 129),
        SWITZERLAND("스위스", 130),
        SPAIN("스페인", 131),
        SLOVAKIA("슬로바키아", 132),
        SLOVENIA("슬로베니아", 133),
        SYRIA("시리아", 134),
        SIERRA_LEONE("시에라 리온", 135),
        SINGAPORE("싱가포르", 136),
        UNITED_ARAB_EMIRATES("아랍에미리트 연합", 137),
        ARUBA("아루바", 138),
        ARMENIA("아르메니아", 139),
        ARGENTINA("아르헨티나", 140),
        AMERICAN_SAMOA("아메리칸 사모아", 141),
        ICELAND("아이슬란드", 142),
        HAITI("아이티", 143),
        IRELAND("아일랜드", 144),
        AZERBAIJAN("아제르바이잔", 145),
        AFGHANISTAN("아프카니스탄", 146),
        ANDORRA("안도라", 147),
        ANTARCTICA("안타티카", 148),
        ANGUILLA("앙귈라", 149),
        ALGERIA("알제리", 150),
        ALBANIA("알바니아", 151),
        ALAND_ISLANDS("알란드 군도", 152),
        ESTONIA("에스토니아", 153),
        ECUADOR("에쿠아도르", 154),
        ETHIOPIA("에티오피아", 155),
        ELSALVADOR("엘살바도르", 156),
        UNITED_KINGDOM("영국", 157),
        BRITISH_VIRGIN_ISLANDS("영령 버진군도", 158),
        INDIAN_OCEAN_TERRITORY("영령 인도양", 159),
        CAYMAN_ISLANDS("영령 캐이맨 군도", 160),
        YEMEN("예맨", 161),
        OMAN("오만", 162),
        AUSTRIA("오스트리아", 163),
        HONDURAS("온두라스", 164),
        WALLIS_AND_FUTUNA("왈라스 & 퓨투나 군도", 165),
        JORDAN("요르단", 166),
        UGANDA("우간다", 167),
        URUGUAY("우루과이", 168),
        UZBEKISTAN("우즈베키스탄", 169),
        UKRAINE("우크라이나", 170),
        WAKE_ISLAND("웨이크 아일랜드", 171),
        YUGOSLAVIA("유고", 172),
        IRAQ("이라크", 173),
        IRAN("이란", 174),
        ISRAEL("이스라엘", 175),
        EGYPT("이집트", 207),
        ITALY("이탈리아", 208),
        INDIA("인도", 209),
        INDONESIA("인도네시아", 210),
        JAPAN("일본", 211),
        JAMAICA("자마이카", 212),
        ZAMBIA("잠비아", 213),
        DJIBOUTI("지부티", 214),
        GIBRALTAR("지브랄타", 215),
        ZIMBABWE("짐바브웨", 216),
        CHAD("챠드", 217),
        CZECH_REPUBLIC("체코공화국", 218),
        CHILE("칠레", 219),
        CAMEROON("카메룬", 220),
        CAPE_VERDE("카보 베르데", 221),
        KAZAKHSTAN("카자흐스탄", 222),
        QATAR("카타르", 223),
        CAMBODIA("캄보디아", 224),
        CANADA("캐나다", 225),
        KENYA("케냐", 226),
        COMOROS("코모로스", 227),
        COSTA_RICA("코스타리카", 228),
        IVORY_COAST("코트디봐르", 229),
        COLOMBIA("콜롬비아", 230),
        CONGO("콩고", 231),
        DEMOCRATIC_REPUBLIC_OF_CONGO("콩고민주공화국", 232),
        CUBA("쿠바", 233),
        KUWAIT("쿠웨이트", 259),
        COOK_ISLANDS("쿡 아일랜드", 260),
        CURACAO("큐라소", 261),
        CROATIA("크로아티아", 262),
        CHRISTMAS_ISLAND("크리스마스 아일랜드", 263),
        KYRGYZSTAN("키르기스스탄", 264),
        KIRIBATI("키리바티", 265),
        TAJIKISTAN("타지크", 266),
        TANZANIA("탄자니아", 267),
        THAILAND("태국", 268),
        TOGO("토고", 269),
        TOKELAU("토켈라우", 270),
        TONGA("통가", 271),
        TURKS_AND_CAICOS_ISLANDS("투르크 & 카이코스 군도", 272),
        TURKMENISTAN("투르크멘", 273),
        TUVALU("투발루", 274),
        TUNISIA("튀니지", 275),
        TURKEY("튀르키예", 276),
        TRINIDAD_AND_TOBAGO("트리니다드 토바고", 277),
        TIMOR_LESTE("티모르", 278),
        PANAMA("파나마", 279),
        PANAMA_CANAL_ZONE("파나마운하지역", 280),
        PARAGUAY("파라과이", 281),
        PARACEL_ISLANDS("파로에 군도", 282),
        PAKISTAN("파키스탄", 283),
        PAPUA_NEW_GUINEA("파푸아 뉴기니", 284),
        PALAU("팔라우", 285),
        PALESTINE("팔레스타인", 286),
        PERU("페루", 287),
        PORTUGAL("포루투갈", 288),
        FALKLAND_ISLANDS("포클랜드 군도", 289),
        POLAND("폴란드", 290),
        PUERTO_RICO("푸에르토리코", 291),
        FRANCE("프랑스", 292),
        METROPOLITAN_FRANCE("프랑스 메트로폴리탄", 293),
        FIJI("피지", 294),
        PITCAIRN_ISLANDS("피트카이른", 295),
        FINLAND("핀란드", 296),
        PHILIPPINES("필리핀", 297),
        HEARD_AND_MCDONALD_ISLANDS("허드 앤 맥도날드 군도", 298),
        HUNGARY("헝가리", 299),
        AUSTRALIA("호주", 300),
        HONG_KONG("홍콩", 301);


        private final String nationName;
        private final Integer code;

        Nation(String nationName, Integer code){
                this.nationName = nationName;
                this.code = code;
        }

        public static Nation ofCode(Integer code){
                return Arrays.stream(Nation.values())
                        .filter(v -> v.getCode().equals(code))
                        .findAny()
                        .orElseThrow(() -> new ApiException(ExceptionEnum.ENUM_NOT_FOUND));
        }

        public static Nation ofValue(String value){
                return Arrays.stream(Nation.values())
                        .filter(v -> v.getNationName().equals(value))
                        .findAny()
                        .orElseThrow(() -> new ApiException(ExceptionEnum.ENUM_NOT_FOUND));
        }

}
