# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: JDK 17 세팅
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: gradlew 실행 권한 추가
      run: chmod +x gradlew

    - name: Gradle 빌드
      run: ./gradlew build

    - name: Docker 빌드
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        cd app-public-api
        docker build -t kurrant_v1 .
        docker tag kurrant_v1 dalicious77/kurrant_v1:${GITHUB_SHA::7}
        docker push dalicious77/kurrant_v1:${GITHUB_SHA::7}
    - name: 배포
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        envs: GITHUB_SHA
        script: |
          docker pull dalicious77/kurrant_v1:${GITHUB_SHA::7}
          docker tag dalicious77/kurrant_v1:${GITHUB_SHA::7} kurrant_v1
          docker stop kurrant_v1
          docker run -d --rm --name kurrant_v1